on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'


jobs:
    test:
        name: Testing types
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            
            - name: Install dependencies
              run: yarn  
                
            - name: Testing
              run: yarn testTypes
    
    lint:
        name: Linting
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            
            - name: Install dependencies
              run: yarn  
                
            - name: Linting
              run: yarn lint